-- Creating Tables
CREATE TABLE university (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    name varchar(255) UNIQUE NOT NULL,
    country varchar(255),
    province varchar(255),
    city varchar(255),
    website varchar(255)
);
CREATE TABLE department (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    field varchar(255) NOT NULL,
    university_id INT,
    FOREIGN KEY (university_id) REFERENCES university (id)
);
CREATE TABLE course (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    code varchar(255) NOT NULL,
    department_id INT,
    subject varchar(255) NOT NULL,
    FOREIGN KEY (department_id) REFERENCES department (id)
);
CREATE TABLE app_user (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    username varchar(255) UNIQUE NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL
);
CREATE TABLE review (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    course_id INT,
    user_id INT,
    rating decimal CHECK (
        rating >= 1
        AND rating <= 5
    ),
    professor varchar(255),
    difficulty decimal CHECK (
        difficulty >= 1
        AND difficulty <= 5
    ),
    comments varchar(255),
    FOREIGN KEY (user_id) REFERENCES app_user (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);
CREATE TABLE student (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    user_id INT,
    university_id INT,
    FOREIGN KEY (user_id) REFERENCES app_user (id),
    FOREIGN KEY (university_id) REFERENCES university (id)
);
CREATE TABLE admin (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES app_user (id)
);
CREATE TABLE news_post (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    admin_id INT,
    title varchar(255) NOT NULL,
    body varchar(255),
    FOREIGN KEY (admin_id) REFERENCES admin (id)
);
CREATE TABLE course_request (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    code varchar(255) NOT NULL,
    student_id INT,
    subject varchar(255) NOT NULL,
    FOREIGN KEY (student_id) REFERENCES student (id)
);
CREATE TABLE university_rating (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    university_id INT,
    student_id INT,
    comments varchar(255),
    safety_rating decimal CHECK (
        safety_rating >= 1
        AND safety_rating <= 5
    ),
    facilities_rating decimal CHECK (
        facilities_rating >= 1
        AND facilities_rating <= 5
    ),
    opportunities_rating decimal CHECK (
        opportunities_rating >= 1
        AND opportunities_rating <= 5
    ),
    FOREIGN KEY (university_id) REFERENCES university (id),
    FOREIGN KEY (student_id) REFERENCES student (id)
);
CREATE TABLE approve (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    course_id INT,
    code varchar(255) NOT NULL,
    admin_id INT,
    FOREIGN KEY (admin_id) REFERENCES admin (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);
-- Seeding Database Data
INSERT INTO university (id, name, country, province, city, website) 
VALUES (1, 'University of Calgary', 'Canada', 'Alberta', 'Calgary', 'https://www.ucalgary.ca/');

INSERT INTO university (id, name, country, province, city, website) 
VALUES (2, 'MIT', 'USA', 'Massachusetts', 'Cambridge', 'https://www.mit.edu/');

INSERT INTO department (id, field, university_id)
VALUES (1, 'Computer Science', 1);

INSERT INTO department (id, field, university_id)
VALUES (2, 'Math', 1);

INSERT INTO department (id, field, university_id)
VALUES (3, 'Computer Science', 2);